server:
  port: 8765
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway
  profiles:
    active: prod
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  config:
    import: optional:configserver:http://127.0.0.1:8888

security:
  jwt:
    token:
      secret-key: ${SECRET_KEY:chave_microservices}
      expire-length: 360000

config:
  routes:
    -
      from: /auth/**
      to: http://localhost:8083
    -
      from: /get
      to: http://httpbin.org:80
  openEndpoints:
    - "/get"
    - "/login"
    - "/user/create"